INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME) VALUES ('US', 'United States');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME) VALUES ('CA', 'Canada');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME) VALUES ('UK', 'United Kingdom');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME) VALUES ('FR', 'France');