INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME, POPULATION) VALUES ('US', 'United States', '100');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME, POPULATION) VALUES ('CA', 'Canada', '200');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME, POPULATION) VALUES ('UK', 'United Kingdom', '300');
INSERT INTO Country (COUNTRY_CODE, COUNTRY_NAME, POPULATION) VALUES ('FR', 'France', '400');